service:
  name: tuneguesser

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: ap-southeast-2
  memorySize: 128

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
