service:
  name: tuneguesser

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: ap-southeast-2
  memorySize: 128
  package:
    individually: true

custom:
  botToken: ${ssm:/tuneguesser-slack-bot-token~true}

functions:
  guess:
    handler: src/guess/index.guess
    package:
      include:
        - src/guess/**
        - src/slack-utils.ts
    environment:
      BOT_TOKEN: ${self:custom.botToken}
    events:
      - http:
          method: post
          path: guess
